### ISSUE TITLE
Non-listy lists in some entries.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#11]
Well, in at least one entry, anyway: see Entry_0200, "Principal Org Primary Area of Expertise - Notes" section.

**Comment by jvasile** [comment]
The original has lines that start with a bullet but no space.  I'll prepend a space to those lines.

This affects a number of entries:
0108
0200
0231
0311
0382
0387
0503
0537
0699
0850
0891
1143
1350
1525
1790

Not surprisingly, it affects multiple columns in some of those entries.

**Comment by jvasile** [comment]
Fixed in [commit 2f88cb714742642c9170a775357783c58241b648](https://github.com/OpenTechStrategies/MacFound/commit/2f88cb714742642c9170a775357783c58241b648), which just replaces bullets with asterisks at the start of lines.
