### ISSUE TITLE
fix-csv should be fix_csv

### ISSUE THREAD

**Issue by jvasile** [OpenTechStrategies/MacFound#13]
[PEP 8 discourages underscores in module and package names.](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)  If somebody wanted to build on fix-csv, they couldn't just do `import fix-csv`.  Instead, they would have to do `python_code = __import__('fix-csv')`. 

I'm not sure if there is anything in fix-csv that somebody might want to build on, but renaming this file will make it more pythonic.

**Comment by kfogel** [comment]
Underscore is discouraged only in package names, not in module names.  In any case, we switched **to** underscore, not away; if we were going to take the advice we thought the PEP was giving, we would have called the thing `fixcsv` :-).  But let's just revert the whole batch.  This isn't a package anyway, it's at most a module, and and hyphen is more common for file names (and easier on most keyboards to type).
