### ISSUE TITLE
Img tags in final output

### ISSUE THREAD

**Issue by jvasile** [OpenTechStrategies/MacFound#18]
Entry 0217 includes &lt;img> tags in the Executive Summary.

You'll also notice the title of the page is just 'H'.  I checked the original csv and that's the original title.

**Comment by jvasile** [comment]
Hrm.  According to [mediawiki documentation](https://www.mediawiki.org/wiki/Help:Images), the way to embed external images in your wiki page is just to put the url of the image.  I guess mediawiki sees the url ends in .png or .jpg and does the right thing.  But entry 217 has images that don't end in file extensions that signal images.  So they'll just come up as links.  I'm not sure there's a good embedding solution here.

**Comment by kfogel** [comment]
Is what's going on in the page with Review Number 6210 the same problem as the above?

**Comment by kfogel** [comment]
Solved with `$wgAllowImageTag = true;` in MediaWiki conf file "LocalSettings.php".

See https://www.mediawiki.org/wiki/Manual:$wgAllowImageTag for more information.
