### ISSUE TITLE
MediaWiki search results don't interpret HTML; can that be improved?

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#24]
Even though things like our `<span style="color: red;" >[empty]</span>` block are displayed correctly on the wiki page, they show up as literal HTML code in MediaWiki search results.  This is probably a known issue with MW search.  Are there any plugins or techniques to fix it?

**Comment by jvasile** [comment]
There are no easy off-the-shelf ways to fix it.  It is, however, a one-line code fix in Mediawiki.  In the LTS version of Mediawiki, which is 1.27.3, from the root of the mediawiki code dir, apply this diff and it should do it.  We could wrap this into an extension, maybe, but I don't actually know mediawiki extension language well enough to do it.  As it is, I had to retune my brain to PHP.

```diff
diff --git a/includes/search/SearchResult.php b/includes/search/SearchResult.php
index 21effbb..3fafebc 100644
--- a/includes/search/SearchResult.php
+++ b/includes/search/SearchResult.php
@@ -147,6 +147,7 @@ class SearchResult {
 		list( $contextlines, $contextchars ) = $this->searchEngine->userHighlightPrefs();
 
 		$h = new SearchHighlighter();
+		$this->mText = strip_tags($this->mText);
 		if ( count( $terms ) > 0 ) {
 			if ( $wgAdvancedSearchHighlighting ) {
 				return $h->highlightText( $this->mText, $terms, $contextlines, $contextchars );
```

This might work in other versions too, but I haven't tested.  Debian testing is on the LTS, so if you installed from that, you should be fine.  I did `git clone https://gerrit.wikimedia.org/r/p/mediawiki/core.git` and got Mediawiki through commit f0e12ae951ef9f6cb359c5ecfcd3739e38f4d29a.  From the `core` directory, this patch applies cleanly with `patch -p 1 < ../../wiki_search_strip_tags.patch`.  IOW, it works with LTS and bleeding edge.  I've checked the patch in as wiki_search_strip_tags.patch.

**Comment by kfogel** [comment]
I'm not even sure it should be an extension -- maybe it's just "a bug fix" to MediaWiki search snippets, and we should offer it upstream as such?
