### ISSUE TITLE
Is there a way to do search within named sections in MediaWiki?

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#25]
Client would like to know :-).

**Comment by jvasile** [comment]
I cannot find one.  Things aren't indexed with page structure in mind in that way.

**Comment by kfogel** [comment]
Agreed.  I couldn't find it on any of

* https://www.mediawiki.org/wiki/Help:Searching
* https://en.wikipedia.org/wiki/Help:Advanced_search
* https://www.mediawiki.org/wiki/API:Search
* https://meta.wikimedia.org/wiki/Help:Section
* Various other likely places on the Internet.

Closing, lest we commit [Error 33](https://en.wikipedia.org/wiki/Error_33).
