### ISSUE TITLE
"unclosed file" warning coming from csvgrep

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#31]
This should really be filed in the `csvkit` repository -- they've encountered it before; see their [issue 693](https://github.com/wireservice/csvkit/issues/693) -- but I haven't investigated in enough detail to file a good bug report yet, and I didn't want to forget it.

Running

    $ time ./wiki-refresh ${OTSDIR}/clients/macfound/eval-system/data` 

produced (amidst all the expected output) this error:

    sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/kfogel/private/work/ots/clients/macfound/eval-system/data/excluded-review-numbers.txt' mode='r' encoding='UTF-8'>

Interestingly, this happened only in the second of two runs, and I was running with the entire sanitization block in `wiki-refresh` commented out (because I'd already completed it) -- that is, the `${SANITIZER}` invocation and the `if...fi` block beneath it were commented out.  Here's the driver script I was using, `doit.sh`:

    #!/bin/sh
    
    cp macfound-partners-csv2wiki-config csv2wiki-config
    echo "Loading partners wiki..."
    time ./wiki-refresh ${OTSDIR}/clients/macfound/eval-system/data
    echo "Done loading partners wiki."
    
    echo ""
    
    echo "Loading internal wiki..."
    cp macfound-internal-csv2wiki-config csv2wiki-config
    time ./wiki-refresh ${OTSDIR}/clients/macfound/eval-system/data
    echo "Done loading internal wiki."

So, given that, here's the relevant output -- the error only happens on second, "internal" run:

    $ ./doit.sh
    Loading partners wiki...
    Stage 1: Sanitizing...
    Done with Stage 1 (sanitizing).
    
    Stage 2: Filtering excluded Review Numbers...
    Done with Stage 2 (filtering excluded Review Numbers).
    
    Creating wiki...
    (...many rows of output omitted...)
    CREATED TOC: "Proposals_TOC"
    Done creating wiki.
    
    50.11user 0.46system 8:55.72elapsed 9%CPU (0avgtext+0avgdata 39464maxresident)k
    8inputs+100944outputs (0major+40166minor)pagefaults 0swaps
    Done loading partners wiki.
    
    Loading internal wiki...
    Stage 1: Sanitizing...
    Done with Stage 1 (sanitizing).
    
    Stage 2: Filtering excluded Review Numbers...
    sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/kfogel/private/work/ots/clients/macfound/eval-system/data/excluded-review-numbers.txt' mode='r' encoding='UTF-8'>
    Done with Stage 2 (filtering excluded Review Numbers).
    
    Creating wiki...
    (...many rows of output omitted...)
    CREATED TOC: "100Change_TOC"
    CREATED CATEGORY: "Crime, Punishment and Rehabilitation"
    CREATED CATEGORY: "Health and Well-Being, Mental Health"
    CREATED CATEGORY: "Public Sector Capacity Building"
    CREATED CATEGORY: "Information and Media Access and Inclusion"
    CREATED CATEGORY: "Health and Well-being: Population and Reproductive Health"
    CREATED CATEGORY: "Health and Well-being, Mental Health"
    CREATED CATEGORY: "Health and Well-Being, Communicable Diseases"
    CREATED CATEGORY: "Crime and Punishment"
    CREATED CATEGORY: "Health and Well-Being, Non-communicable Diseases"
    CREATED CATEGORY: "Civil Society and Governance"
    CREATED CATEGORY: "Food Security"
    CREATED CATEGORY: "Public Safety"
    CREATED CATEGORY: "Refugees and Victims of Conflict"
    CREATED CATEGORY: "Human Trafficking"
    CREATED CATEGORY: "Conservation and Biodiversity"
    CREATED CATEGORY: "Health and Well-being, Diagnostics"
    CREATED CATEGORY: "Privacy Rights"
    CREATED CATEGORY: "International Peace and Security"
    CREATED CATEGORY: "Education"
    CREATED CATEGORY: "Health and Well-Being, Other, Not Elsewhere Listed"
    CREATED CATEGORY: "Resilience Against Natural Disasters"
    CREATED CATEGORY: "Transportation"
    CREATED CATEGORY: "No Primary Thematic Area Selected"
    CREATED CATEGORY: "Racial, Ethnic and Gender Justice, Equity and Inclusion"
    CREATED CATEGORY: "Resilience against Climate Change"
    CREATED CATEGORY: "Arts and Culture"
    CREATED CATEGORY: "Health and Well-Being, Population and Reproductive Health"
    CREATED CATEGORY: "Health and Well-Being, Diagnostics"
    CREATED CATEGORY: "Resilience Against Climate Change and Environmental Damage"
    CREATED CATEGORY: "Affordable and Clean Energy"
    CREATED CATEGORY: "Housing and Homelessness"
    CREATED CATEGORY: "Social Protection and-or Safety Nets"
    CREATED CATEGORY: "Health and Well-being, Other, not elsewhere listed"
    CREATED CATEGORY: "Health and Well-being, Non-Communicable Diseases"
    CREATED CATEGORY: "Sustainable Cities, Communities and Regions"
    CREATED CATEGORY: "Assistive Technology"
    CREATED CATEGORY: "Resilience against Natural Disasters"
    CREATED CATEGORY: "Clean Water and Sanitation"
    CREATED CATEGORY: "Transitional Justice"
    CREATED CATEGORY: "Economic Opportunity"
    CREATED CATEGORY: "Health and Well-being: Communicable Diseases"
    Done creating wiki.
    
    86.06user 0.56system 8:55.98elapsed 16%CPU (0avgtext+0avgdata 39272maxresident)k
    0inputs+100944outputs (0major+41050minor)pagefaults 0swaps
    Done loading internal wiki.

**Comment by jvasile** [comment]
+1 I saw it too, though I collected no data as it was harmless AFAICT.

**Comment by kfogel** [comment]
Closing.  This is now reported upstream ([issue 838](https://github.com/wireservice/csvkit/issues/838)) with patch submitted ([PR 839](https://github.com/wireservice/csvkit/pull/839)).

**Comment by kfogel** [comment]
Upstream merged this, btw.
