### ISSUE TITLE
Some CSV entries open an HTML table but do not close it, leading to misformatted wiki pages.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#4]
Some wiki pages are misformatted because there are cells in the CSV that (post-sanitization) include an opening "&lt;table&gt;" HTML element but never close that element.  In the resultant wiki page, all the sections after the problem section are thus made part of the table, so everything from that point on is indented inward to the right and ugliness ensues.

I don't yet know whether this is a bug in the sanitization process (could be that something is being unescaped too much / not enough) or a bug in the original data.

You can see examples of this in Entry_0700 (starting in the section derived from column 46, "Tactics and Technology"), and in Entry_1700 (column 47, "Timeline and Key Milestones").

Entry_1900 might also be worth looking at, because it shows a stray "&lt;tbody&gt;" at the beginning of column 47 ("Timeline and Key Milestones"), and then a stray "&lt;tbody&gt;  &lt;/tbody&gt;" at the beginning of 49 ("Risk Assessment"), although the table in the rest of that section does appear to close properly and present reasonably well .  (Notice that that page also has a bunch of other non-ideal inline formatting problems, of course: spurious "&lt;p&gt;" markers, "&lt;a href=...&gt;", etc.  But let's take one thing at a time.)

To see all instances of this problem in the CSV, make this temporary patch to `wiki-refresh` and re-run:

    --- wiki-refresh
    +++ wiki-refresh
    @@ -86,7 +86,7 @@ SANITIZE="${MACFOUND_DIR}"/fix-csv
     
     # First we're working on sanitization (wiki conversion comes later).
     echo "Sanitizing..."
    -${SANITIZE} "${CSV_INPUT}" "sanitized-${CSV_INPUT}"
    +${SANITIZE} --show-table-problem "${CSV_INPUT}" "sanitized-${CSV_INPUT}"
     # ...the above command produces "sanitized-${CSV_INPUT}".
     echo "Done sanitizing."
     echo ""

The output will be noisy; search for "**DEBUG:**" to see each problem cell.

The problem happens in lots of entries, by far most often in column 46 ("Tactics and Technology"), but here is the full set of columns where it is known to happen:

    46) Tactics and Technology
    45) Other Work Location
    52) Organizational Capacity
    53) Budget Narrative
    49) Risk Assessment
    47) Timeline and Key Milestones
    48) Evidence of Effectiveness
    54) Resource Requirements and Sustainability
    50) Plan Monitoring/Evaluation/Learning
    51) Previous Performance
    38) Why Collaboration is Effective
    39) Problem Statement
    55) Other Considerations
    36) Principal Organization Primary Thematic Area of Proposed Solution - Notes
    56) Charitable Purpose

**Comment by jvasile** [comment]
Defect is in the original.  See, e.g., Entry 0700, column 48, "Tactics and Technology".  It has a text paragraph, then it opens a table but never closes it.  It cuts off and leaves a td open.  The resulting table is just a couple of headers and one body cell filled in.  This raises the question of whether the original got truncated somewhere on its way to us.

Regardless of whether the original is busted, we should at least close any open tables, so I'll work on that next.

**Comment by jvasile** [comment]
Partially addressed in [commit db03880849f264cf3c0f7da73743dac865472631](https://github.com/OpenTechStrategies/MacFound/commit/db03880849f264cf3c0f7da73743dac865472631), which ensures HTML is well-formed.  That will close all dangling tags.  There are still table artifacts in, e.g., 0700 column 48, "Tactics and Technology", so there's more work to be done, but this is a good next step.

The big downside here is that between this patch and [the one that addressed issue 9](https://github.com/OpenTechStrategies/MacFound/commit/bddca5903abbc09468dacb6391ec67ce81acc167), fix-csv parses cells with beautifulsoup multiple times.  This is pretty slow.  We should at some point refactor to soupify things just once, then operate on them in all the various ways we need, then return unicode(soup).

**Comment by jvasile** [comment]
These tbody tags should be removed.  Mediawiki doesn't like them.  Done in [csv2wiki commit 3c514d94fdbf66beff333c103a8daf29089f18cf](https://github.com/OpenTechStrategies/csv2wiki/commit/3c514d94fdbf66beff333c103a8daf29089f18cf).
