### ISSUE TITLE
In some entries, boldface starts but never ends.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#9]
In some entries, boldface formatting starts, but then never ends -- it continues on through all the remaining sections and content of the page.

An example is Entry_1300  (which, of course, is in the 1% (`--pare=100`) subset, so you should get it even on a fast dev conversion run).  In that entry, the problem starts in column 46, "Tactics and Technology".

**Comment by jvasile** [comment]
It's not quite the case that boldface never ends.  Rather, the html in the csv bolds everything, paragraph by paragraph (or in some cases paragraph chunk by paragraph chunk).  I'm tempted to apply a rule that says "if everything is emphasized, then nothing is emphasized" and therefore we can strip the `<strong>` tags because emph = !emph.  I'll see how that works.

**Comment by kfogel** [comment]
On Apr 26, 2017 7:10 PM, "James Vasile" <notifications@github.com> wrote:

It's not quite the case that boldface never ends. Rather, the html in the
csv bolds everything, paragraph by paragraph (or in some cases paragraph
chunk by paragraph chunk).

Yes, but the "sanitized" CSV or the original?  I.e., are we causing the
problem, or is it in the original?

I'm tempted to apply a rule that says "if everything is emphasized, then
nothing is emphasized" and therefore we can strip the <strong> tags because
emph = !emph. I'll see how that works.

I'd expect there are some entries that use <strong> in a meaningful way,
though, aren't there?

**Comment by jvasile** [comment]
Based on some spot checking, the `<strong>` tags are in the original.

We can distinguish between meaningful and not.  In cases where `<strong>` isn't applied to the whole entry, we can leave it.  I'll adjust fix-csv to do this.  It occurs to me that this is the kind of sanitizing routine that should be available in csv2wiki and it should be user-enabled in the config file, perhaps on a column-by-column basis.  If you agree, make a ticket for that in csv2wiki and I'll put it in the queue.

**Comment by jvasile** [comment]
Fixed in [commit bddca5903abbc09468dacb6391ec67ce81acc167](https://github.com/OpenTechStrategies/MacFound/commit/bddca5903abbc09468dacb6391ec67ce81acc167).
